include:
# Left keyboard - peripheral
- board: nice_nano
  shield: charybdis_left

# Right keyboard - central (standalone mode without dongle)
- board: nice_nano
  shield: charybdis_right_standalone
  snippet: studio-rpc-usb-uart
  cmake-args: -DCONFIG_ZMK_STUDIO=y

# Settings reset for nice_nano
- board: nice_nano
  shield: settings_reset
